### ISSUE TITLE
Правки

### ISSUE THREAD

**Issue by modanets** [OlgaKlekot/EPAM-PHP-mentee#1]
- тут https://github.com/OlgaKlekot/EPAM-PHP-mentee/blob/master/beginnings/task2.php#L12 переменные мы пишем в CamelCase (посмотри на PSR1 и PSR2 стандарты http://www.php-fig.org/psr/psr-1/ и http://www.php-fig.org/psr/psr-2/)
 - тут https://github.com/OlgaKlekot/EPAM-PHP-mentee/blob/master/beginnings/task2.php#L20 - не совсем понятно зачем так много знаков доллар =) Посмотри внимательнее, может там есть один лишний. Для практики - придумай предложение подлинее и вставь в него минимум 3 переменные используя ```${var}``` запись (в этом же файле).

**Comment by OlgaKlekot** [comment]
виправила)

**Comment by modanets** [comment]
Супер!
