### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by modanets** [OlgaKlekot/EPAM-PHP-mentee#2]
- а можешь тут, заюсать HEREDOC (http://php.net/manual/en/language.types.string.php) https://github.com/OlgaKlekot/EPAM-PHP-mentee/blob/master/beginnings/task2.php#L28 для практики?
 - тут https://github.com/OlgaKlekot/EPAM-PHP-mentee/blob/master/beginnings/task3.php#L5 переделай плз все переменные в **echo** на ```${var}``` как в предыдущей задаче. На будущее, мы переменные в строку добавляем либо так: ```${var}``` либо так ```{$var}``` либо рвем строку и соединяем разделителями ```'какая-то строка ' . $var . ' продолжение строки'```

**Comment by OlgaKlekot** [comment]
done) а інші таски - ок?
